# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 20:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mldb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='color',
            field=models.CharField(default=b'#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(b'#[0-9a-fA-F]{6}')]),
        ),
        migrations.AddField(
            model_name='character',
            name='outline',
            field=models.CharField(default=b'#cccccc', max_length=7, validators=[django.core.validators.RegexValidator(b'#[0-9a-fA-F]{6}')]),
        ),
    ]
